source 'https://rubygems.org'
group :test, :development do
  gem 'rake'
end
gem 'motion-layout'
gemspec

#gem 'teacup', :path => '/Users/ploskon/devel/examples/teacup'
source 'https://rubygems.org'
#gem 'rake'
gem 'bubble-wrap'
gem 'motion-yaml'
